// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Thi.Data;

#nullable disable

namespace Thi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250605063247_UpdateSinhVienHinhLength")]
    partial class UpdateSinhVienHinhLength
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Thi.Models.ChiTietDangKy", b =>
                {
                    b.Property<int>("MaDK")
                        .HasColumnType("int");

                    b.Property<string>("MaHP")
                        .HasColumnType("char(6)");

                    b.HasKey("MaDK", "MaHP");

                    b.HasIndex("MaHP");

                    b.ToTable("ChiTietDangKys");
                });

            modelBuilder.Entity("Thi.Models.DangKy", b =>
                {
                    b.Property<int>("MaDK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDK"));

                    b.Property<string>("MaSV")
                        .HasColumnType("char(10)");

                    b.Property<DateTime?>("NgayDK")
                        .HasColumnType("datetime2");

                    b.HasKey("MaDK");

                    b.HasIndex("MaSV");

                    b.ToTable("DangKys");
                });

            modelBuilder.Entity("Thi.Models.HocPhan", b =>
                {
                    b.Property<string>("MaHP")
                        .HasColumnType("char(6)");

                    b.Property<int?>("SoTinChi")
                        .HasColumnType("int");

                    b.Property<string>("TenHP")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaHP");

                    b.ToTable("HocPhans");

                    b.HasData(
                        new
                        {
                            MaHP = "CNTT01",
                            SoTinChi = 3,
                            TenHP = "Lập trình C"
                        },
                        new
                        {
                            MaHP = "CNTT02",
                            SoTinChi = 2,
                            TenHP = "Cơ sở dữ liệu"
                        },
                        new
                        {
                            MaHP = "QTKD01",
                            SoTinChi = 2,
                            TenHP = "Kinh tế vi mô"
                        },
                        new
                        {
                            MaHP = "QTDK02",
                            SoTinChi = 3,
                            TenHP = "Xác suất thống kê 1"
                        });
                });

            modelBuilder.Entity("Thi.Models.NganhHoc", b =>
                {
                    b.Property<string>("MaNganh")
                        .HasColumnType("char(4)");

                    b.Property<string>("TenNganh")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaNganh");

                    b.ToTable("NganhHocs");

                    b.HasData(
                        new
                        {
                            MaNganh = "CNTT",
                            TenNganh = "Công nghệ thông tin"
                        },
                        new
                        {
                            MaNganh = "QTKD",
                            TenNganh = "Quản trị kinh doanh"
                        });
                });

            modelBuilder.Entity("Thi.Models.SinhVien", b =>
                {
                    b.Property<string>("MaSV")
                        .HasMaxLength(10)
                        .HasColumnType("char(10)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Hinh")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaNganh")
                        .IsRequired()
                        .HasColumnType("char(4)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.HasKey("MaSV");

                    b.HasIndex("MaNganh");

                    b.ToTable("SinhViens");

                    b.HasData(
                        new
                        {
                            MaSV = "2280600791",
                            GioiTinh = "Nam",
                            Hinh = "/images/sv1.jpg",
                            HoTen = "Đặng Trí Hải",
                            MaNganh = "CNTT",
                            NgaySinh = new DateTime(2004, 10, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MaSV = "9876543210",
                            GioiTinh = "Nữ",
                            Hinh = "/images/sv2.jpg",
                            HoTen = "Nguyễn Thị B",
                            MaNganh = "QTKD",
                            NgaySinh = new DateTime(2000, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Thi.Models.ChiTietDangKy", b =>
                {
                    b.HasOne("Thi.Models.DangKy", "DangKy")
                        .WithMany("ChiTietDangKys")
                        .HasForeignKey("MaDK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Thi.Models.HocPhan", "HocPhan")
                        .WithMany("ChiTietDangKys")
                        .HasForeignKey("MaHP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DangKy");

                    b.Navigation("HocPhan");
                });

            modelBuilder.Entity("Thi.Models.DangKy", b =>
                {
                    b.HasOne("Thi.Models.SinhVien", "SinhVien")
                        .WithMany("DangKys")
                        .HasForeignKey("MaSV");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("Thi.Models.SinhVien", b =>
                {
                    b.HasOne("Thi.Models.NganhHoc", "NganhHoc")
                        .WithMany("SinhViens")
                        .HasForeignKey("MaNganh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NganhHoc");
                });

            modelBuilder.Entity("Thi.Models.DangKy", b =>
                {
                    b.Navigation("ChiTietDangKys");
                });

            modelBuilder.Entity("Thi.Models.HocPhan", b =>
                {
                    b.Navigation("ChiTietDangKys");
                });

            modelBuilder.Entity("Thi.Models.NganhHoc", b =>
                {
                    b.Navigation("SinhViens");
                });

            modelBuilder.Entity("Thi.Models.SinhVien", b =>
                {
                    b.Navigation("DangKys");
                });
#pragma warning restore 612, 618
        }
    }
}
